# Generated by Django 5.2.9 on 2025-12-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
    ]
